### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by chaveamin** [Nikba-Creative-Studio/WHMCS-Telegram-Notifications#2]
Seems like windows and also chrome detects zip file as a virus. please consider checking the files
![Screenshot 2024-10-25 092735](https://github.com/user-attachments/assets/3799af69-a176-4713-8dc1-99252107b498)
![Screenshot 2024-10-25 092837](https://github.com/user-attachments/assets/974c841c-45ae-4834-bff2-aee8dea8a7ba)

**Comment by Nikba-Creative-Studio** [comment]
Hi, this project is an open-source project. 
The entire source code, which needs to be installed, is available here on GitHub. 
Any capable developer can analyze and install it. 
The fact that your antivirus system detects it your local problem. 
Additionally, it does not need to be in an archive; it is installed in a folder on the server. 
Please read the instructions carefully. 
We cannot influence what happens on your computer. 
Thank you for your understanding.
